### ISSUE TITLE
收付款计划调整，已付款及已收款信息推送规则

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-dzug#167]
1.收款/付款计划发生调整，系统会向财务总监及经营者发送推送通知（手机及电脑端，电脑端链接可点入）（取我方单位的财务总监及总经理）提示语：“合同名称”:+原“计划收/付款日期”+计划收/款+“本次收/付款金额”+已被修改
2.当超过收/付款计划时间5天，执行人还没有打勾确认的话，给我方单位的财务总监及总经理发送推送提醒（手机及电脑端，电脑端链接可点入），提示语：“合同名称”:+原“计划收/付款日期”+的+“本次收/付款金额”+未付款/未收款
3.收款计划中收款计划时间到起前7天给我方单位的出纳发送推送提醒（手机及电脑端），提示语：“合同名称”：+预计+“计划收/付款日期”+将有+“本次收款金额”+到账
4.NC的收款记录进入业财台账后，系统将会给执行人发送款项到账提示信息；手机及电脑端，电脑端链接可点入）提示语：“合同名称”：+“收款金额”+已到账
5.业财台账中付款单的支付状态为结算成功（5）；手机及电脑端，电脑端链接可点入）  提示语：“合同名称”：+“付款金额”+已支付

**Comment by baozhoutao** [comment]
收/付款计划变化 提示语示例：
  测试付款1022：原2019-11-21计划付款10000已被修改

**Comment by baozhoutao** [comment]
steedos-config.yml 需要添加配置：*/5 * * * * 表示每5分钟计算一次要提醒的数据
```
dzug_notification:
  cron: "*/5 * * * *"
  contract_payments_expiredDay: 5
  contract_receipts_expiredDay: 5
  contract_receipts_AdvanceDay: 7
```
